"use client"

import { DonutChart } from "@/components/tremor/DonutChart"
import { Card } from "@/components/tremor/Card"
import {
  chartColors,
  cx,
  type AvailableChartColorsKeys,
} from "@/components/tremor/utils"
import type { CustomerMargin } from "@/lib/contracts/verdict"
import { money, percent } from "./format"

const palette: AvailableChartColorsKeys[] = [
  "blue",
  "emerald",
  "cyan",
  "indigo",
  "sky",
  "violet",
]

export function ProfitMixDonut({
  customers,
  currency,
}: {
  customers: CustomerMargin[]
  currency: string
}) {
  const winners = customers
    .filter((c) => c.trueMargin > 0)
    .sort((a, b) => b.trueMargin - a.trueMargin)

  const totalProfit = winners.reduce((s, c) => s + c.trueMargin, 0)
  const lost = customers
    .filter((c) => c.trueMargin < 0)
    .reduce((s, c) => s + Math.abs(c.trueMargin), 0)
  const loserCount = customers.filter((c) => c.trueMargin < 0).length

  const data = winners.map((c) => ({
    name: c.customerName,
    value: c.trueMargin,
  }))

  return (
    <Card className="flex h-full flex-col">
      <h3 className="text-base font-semibold text-gray-900 dark:text-gray-50">
        Where profit comes from
      </h3>
      <p className="text-sm text-gray-500 dark:text-gray-400">
        Gross margin generated by your profitable accounts
      </p>

      <div className="mt-4 flex flex-col items-center gap-6 sm:flex-row">
        <DonutChart
          data={data}
          category="name"
          value="value"
          colors={palette}
          showLabel
          label={money(totalProfit, currency)}
          valueFormatter={(v) => money(v, currency)}
          className="mx-auto h-36 w-36 shrink-0"
        />

        <ul className="w-full space-y-2">
          {winners.map((c, i) => (
            <li
              key={c.customerId}
              className="flex items-center justify-between gap-2 text-sm"
            >
              <span className="flex min-w-0 items-center gap-2">
                <span
                  className={cx(
                    "size-2.5 shrink-0 rounded-sm",
                    chartColors[palette[i % palette.length]].bg,
                  )}
                  aria-hidden
                />
                <span className="truncate text-gray-700 dark:text-gray-300">
                  {c.customerName}
                </span>
              </span>
              <span className="shrink-0 font-medium tabular-nums text-gray-900 dark:text-gray-50">
                {percent(c.trueMargin / totalProfit)}
              </span>
            </li>
          ))}
        </ul>
      </div>

      {lost > 0 && (
        <p className="mt-4 border-t border-gray-100 pt-3 text-xs text-gray-500 dark:border-gray-800 dark:text-gray-400">
          Before{" "}
          <span className="font-semibold text-red-600 dark:text-red-500">
            {money(lost, currency)}
          </span>{" "}
          drained by {loserCount} money-losing{" "}
          {loserCount === 1 ? "account" : "accounts"}.
        </p>
      )}
    </Card>
  )
}
